### ISSUE TITLE
Improve documentation for configuration

### ISSUE THREAD

**Issue by lervag** [idanarye/vim-omnipytent#10]
The options are not all documented properly. Some issues are:

1. The options should be documented consistently in the "CONFIGURATION" section. Right now, only the "g:omnipytent_filePrefix" option is properly documented.
2. The "g:omnipytent_selectionUI" option is not described at all.

**Comment by idanarye** [comment]
I do want to keep the full description of each configuration option in the section where it makes most sense. I put the `g:omnipytent_filePrefix` in there because it is something you must set before you can use Omnipytent, and the others are linked to the relevant section...

But maybe it would be clearer and more consistent if I add a _BEFORE YOU BEGIN_ section for the `g:omnipytent_filePrefix` and make all the entries under _CONFIGURATION_ into links to the proper place + short description?

**Comment by idanarye** [comment]
Even better - I move the `g:omnipytent_filePrefix` description to the _CREATING TASKS_ section and refer the user to this section in the _INTRODUCTION_.

**Comment by lervag** [comment]
Great, I agree this works well.
