### ISSUE TITLE
Feature: Global task files

### ISSUE THREAD

**Issue by lervag** [idanarye/vim-omnipytent#12]
It seems I will be making very similar task files for some projects. I am curious what you think about adding a filetype specific global task file in the same spirit as UltiSnips. I.e., if the desired task is not found in the CWD or project root, then look in e.g. `~/.vim/Omnipytent/<filetype>.py` or in `~/.vim/Omnipytent/common.py`. This should adhere to the `runtimepath` variable, of course.

A minor extra would then be to let `OPedit` open either the local or the global file.

**Comment by idanarye** [comment]
See `:help omnipytent.ext`. For example, I have this as my "global task file": https://github.com/idanarye/vimConfig/blob/master/0my-configurations/omnipytent/idan.py

And then I just add:
```python
from omnipytent.ext.idan import *
```

To every project and to get everything from it. With #13 you could add that import automatically.

**Comment by lervag** [comment]
Ok, this seems close to what I want. What happens if I define a task `run` inside the extension, then a new task `run` in a local file? Will the local version have priority?

Also, how could I use this to get filetype specific (global) targets? I guess I could use names `<filetype>.py` and then import with e.g. `from omnipytent.ext.ft_vim import *`, but in this case it would be convenient if the template could interpolate the filetype.

**Comment by idanarye** [comment]
> Ok, this seems close to what I want. What happens if I define a task run inside the extension, then a new task run in a local file? Will the local version have priority?

Yes. Omnipytent's uses Python's name resolution rules. The tasks file is a module, and the tasks are the items of that module. If you import a `run` task from the extension `tasks_file.module.run` will point to that task. If you define your own `run` task in the tasks file, `tasks_file.module.run` will point to the new task, and nothing in `tasks_file.module` will be pointing to the `run` task from the extension anymore.

> Also, how could I use this to get filetype specific (global) targets?

Omnipytent is not a very opinionated plugin, and tries to support any workflow the user wants to have. But there is one thing it is very opinionated about - that tasks files are project-oriented, not filetype-oriented. When you work on a C project you work on a C project - and it doesn't matter if you are in a `.c`/`.h` file or in the `Makefile` or in some `.txt` file that you want to use as test input. You can also work on a `.py` file because you are using pytest to test the executable, and you'd still be working on a C project - **not** a Python project. The tasks you'll need - build the project, run the tests, run the executable on that `.txt` file I mentioned - are going to be the same no matter which file of the project happens to be opened at your editor right now.

I understand this is very alien to the usual Vim way of configuration, that assumes that when you are working on a C project you'll spend most of your time in `.c`/`.h` files so it's easy to just put all the special commands, keymaps and settings as buffer-local configuration under `ftplugin/c.vim` or with `:autocmd FileType c`. And if you want global commands that will always be available to you when you use a certain filetype you can still use that, but the whole point of Omnipytent is to be able to write project-specific tasks.

So, I can interpret your request in two ways:

1. The `omnipytent.ext.ft_vim` extension that you mentioned, for example, is not really for the `.vim` filetype but for Vim plugin development. You want to go to a Vim project, open one of the `.vim` files, and run `:OPe` - and have the tasks file template recognize the file type and generate a basic tasks file for a Vim plugin project.

    If this is the case, I strongly believe the template should be smarter and look at more than just the filetype. Consider Java for example - if you generate the template from a `.java` file, should it generate tasks (or import statement for an extension module with said tasks) for an Ant project, a Maven project or a Gradle project? These all have different commands for building, running and testing the code, and a single developer could work on Java projects with different build systems - because you don't always choose the build system for group projects.

    Also, using the filetype feels a bit coincidental. When you first generate the tasks file you must be aware of which filetype you are on, and if you make a mistake you'll need to delete it and generate it again. Say you were using `:OPe` to generate a custom project-specific task when you were editing some `.xml` file, and now instead of generating a tasks file for a C# project it generated one for an XML project (which would probably be the default tasks file, because XMl project is not really a thing). But you didn't notice this, and wrote your custom tasks, and now you want to use the common C# project tasks - but they aren't there so you need to either add them manually or delete and recreate the tasks file and copy the project-specific tasks to the new tasks file.

    So instead I think the template should try to recognize the project type. Maybe it could be a function, and could look at files in the project?

    Alternatively - Omnypytent's predecessor - Integrake - had a command called [`:IRgrab`](https://github.com/idanarye/vim-integrake#templates) that allows you to specify a template's name and generate a tasks file from that template. I didn't implement it in Omnipytent because I figured it's better to use a proper template engine, but maybe something like this could be the solution to your problems?

2. You really do want filetype-oriented commands, but you want to power these commands with Python's expressiveness and Omnipytent's extensive facilities, async tasks reactor, and tasks file hot reloading. While this is not what Omnipytent was meant for, I can understand why you'd want to use it for that. In this case, instead of polluting the tasks file, I think it'll be better to introduce a new mechanism - _**G**lobal **O**mni**p**ytent_. The `:GOP` command (pun intended) will use a global tasks file instead of the local one. You could have multiple global task files, and `:GOP`'s first argument will be that filetype. Then, in the `ftplugin/vim.vim`, you could do:

    ```vim
    command -buffer -nargs=? FOP GOP ft_vim <args>
    ```

    And now `:FOP` in Vim will run tasks from the global `ft_vim.py` task file when you are in `.vim` files. Maybe I could also write some command or function to create the whole set (`FOPedit` and friends) and add proper completion...

**Comment by lervag** [comment]
> But there is one thing it is very opinionated about - that tasks files are project-oriented, not filetype-oriented.

Excellent point, and I agree this makes sense!

My main point is to avoid having to copy tasks around because I believe I will very often use the same type of tasks for similar projects. So, in this sense, I think your number one pretty much covers what I would want. Your number two might also be useful, but I am not so sure.

If I understand your earlier comment correctly, then I can do this:

```
> tree -d -L 1 .vim
.vim
├── autoload
├── bundle
├── omnipytent
│   ├── fortran.py
│   └── python.py
├── personal
├── spell
├── swap
└── UltiSnips
```

where `fortran.py` and `python.py` include common tasks for Fortran and Python type projects. Now I can add

```python
from omnipytent.ext.python import * # or .fortran
```

and it will load the common tasks in the current project. If I understand correctly, then I believe this actually covers my general need. However, I think it would be good/nice to have this part better documented and explained, as I was not able to realize this "workflow" from the documentation.

**Comment by idanarye** [comment]
Yea... the `omnipytent.ext` section make it seem like the purpose of this feature is for Vim plugins to offer Pythonic interfaces that work well with Omnipytent, and it says nothing about this other usage... I'll want to mention this usage there, and also write an entry in the wiki (the idea is to make the vimdoc a reference manual with technical description and the wiki a FAQ with examples)

**Comment by lervag** [comment]
Great, I think this looks good. I'll open a new issue if I after some time of use change my mind.
