### ISSUE TITLE
[feature request] Allow project root as destination for the task file

### ISSUE THREAD

**Issue by lervag** [idanarye/vim-omnipytent#2]
# Context

Assume prefix is `.kyl` and python3. Consider this file structure:

```
.
├── doc
│   └── docs.txt
├── README
├── .kyl.omnipytent.3.py
└── src
    ├── file1
    ├── file2
    ├── sub1
    │   ├── file1
    │   └── file2
    └── sub2
        ├── file1
        └── file2
```

Assume that the omnipytent task file has one task: `test`.

# Current behaviour

If I open `src/sub1/file1`, then do `:OP test`, the `test` task will run. If I do `:OPedit {task}`, it will create the file `src/sub1/.kyl.omnipytent.3.py` with a template for `{task}`.

# Desired behaviour

Similar to above, but for `:OPedit`, one should prefer to put the task file at project root, not at CWD. It should be possible to specify task files in parent directories as well, and `OP {task}` should run the "closest" defined task.

As an example, CtrlP has an option to specify the working path:

```
                                                   *'g:ctrlp_working_path_mode'*
When starting up, CtrlP sets its local working directory according to this
variable:
  let g:ctrlp_working_path_mode = 'ra'

  c - the directory of the current file.
  a - the directory of the current file, unless it is a subdirectory of the cwd
  r - the nearest ancestor of the current file that contains one of these
      directories or files:
      .git .hg .svn .bzr _darcs
  w - modifier to "r": start search from the cwd instead of the current file's
      directory
  0 or <empty> - disable this feature.

```

I think Omnipytent should have a similar option, as I understand that users might have different opinions on what should be the behaviour.

# Extra

If I do `:OPedit {task}`, it would be convenient if this searches the directory tree upwards, locates all task file candidates. If any of these candidates have a task `{task}`, this file is opened. If more than one such file is found, then select the closest to the current file. If no candidate is found, then create a new task file as suggested above.

**Comment by idanarye** [comment]
The main issue I had with this is the CWD when running the command. If your task is:
```python
@task
def test(ctx):
    BANG << 'test-runner-tool'
```
And you run `:OP test`, should it run `test-runner-tool` from `src/sub1` or from the project's root?

But - I guess if this feature is off by default, and the user has to config the task file location behavior, they can also config where the commands will run from. I'll also add `ctx.proj_dir`, `ctx.file_dir` and `ctx.cur_dir` to allow explicitly using these paths in the tasks.

I hope to get to it during the weekend.

As for the "Extra" - I'm a strong believer in one-tasks-file-per-project. If you are in `./src/sub1/file1` and create a new task it should be created in the root `.kyl.omnipytent.3.py` - not in `./src/sub1`. My assumption is that if you are creating that task from `./src/sub1/file1` it's not because that task is specific to `./src/sub1/` - it's because you have to be somewhere and that somewhere happens to be one of the files under `./src/sub1/`.

Moving away from one-tasks-file-per-project is complicating the model, and I'm not convinced it has a justifying use-case. Even if there was, I would like to consider more structured architectures(like master task file and slave task files, or annotating tasks to only allow them in subdirs)

**Comment by lervag** [comment]
Thanks for the quick response!

I can see your point regarding the CWD when running. I agree it seems smart to add the various `_dir`s to the `ctx`. I think there should be four dirs, though. In addition to the ones you propose, one should also have something like `ctx.task_file_dir`.

I would propose that the default task runner directory should be the same location as task file, and not the current CWD, since this should work regardless of `[no]autochdir`.

Regarding the support for multi-layer task files: I can see your point. Although I still think this would be a convenient feature, I also think it will not be something I would really use that much. To give a use case for this: When developing [vimtex](https://github.com/lervag/vimtex), I tend to create test directories per issue. Some of these tests have specific ways to run, whereas others are more generic. By allowing a top level task file to specify the generic test recipe and then add specific ones when desired, I could keep the same user mappings to get the desired functionality, regardless of which issue I'm working on.

----

One more extra (I could open a new issue, if you want): It would be convenient with a command to repeat the last task (with same arguments). Something like `:OPRerun`.

**Comment by idanarye** [comment]
Yea, you should open new tickets instead of these "extra"s.

As for your test dirs scenario - I think a master&slaves model, or a a local configuration model, will work better - but let's discuss it in another ticket that you'll open.

**Comment by lervag** [comment]
Ok, I've opened new issues for the extras. This means the current issue is isolated to *properly detect project root*. As you mentioned, it will also be very useful to have the relevant paths added to `ctx`:

```
ctx.proj_dir
ctx.file_dir
ctx.cur_dir
ctx.task_file_dir
```

The last, `ctx.task_file_dir` will most likely only be relevant if you would ever consider #4.

**Comment by lervag** [comment]
I don't think this is quite finished, as vim-omnipytent still does not recognize the project root. I.e., if I open a file in `./subdirectory`, then do `:OPedit test`, it will create `./subdirectory/.omnipytent.3.py`. I would expect that the file is created at `./.omnipytent.3.py`.

**Comment by idanarye** [comment]
Never like that heuristic(deals terribly with submodules), but OK

**Comment by lervag** [comment]
I'm not quite sure I understand which heuristic you're referring to. My initial point in this issue is that for people like me who use `autochdir`, Vim's CWD is typically the same location as the current file. Thus adding the task file at this WD will more often than not be wrong. At least for those who use `autochdir`.

Or perhaps I misunderstand what you meant?

**Comment by idanarye** [comment]
The heuristic used in CtrlP is that the project root contains `.git`, `.hg` `.svn`, `.bzr` or `_darcs`. I consider it a heuristic because:

- Nothing guarantees the project root to contain them - what if you are using some other source control?
- What if you aren't using a source control, but for some reason an unrelated parent directory contains one? e.g. - what if you have made your home directory a Git workdir so you can put your dotfiles in GitHub?
- What if you create the tasks file while editing a file in a Git submodule? The tasks file will be created in the root of the submodule...

Still - heuristics should be accurate enough when they are customized, so when there is no tasks file I'm going to have the default always use the current directory and allow the user to set a list of special files to set their own heuristics.

**Comment by lervag** [comment]
I agree these are heuristics. As such, I find your implementation from #6 to be adequate. It seems to work well both for the "simple cases" of projects with VCS roots as well as other projects (where I might have to manually add/touch the task file).

**Comment by idanarye** [comment]
> (where I might have to manually add/touch the task file)

One of the things we'll have to do for #4 is to allow the user to specify what they want to put where without manually adding tasks file**s**.

**Comment by lervag** [comment]
Great, thanks! Very nice work!
